name: sembast
version: 3.7.1
description: NoSQL persistent embedded file system document-based database for Dart VM and Flutter with encryption support.
homepage: https://github.com/tekartik/sembast.dart/tree/master/sembast
topics:
  - nosql
  - database

funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  meta: '>=1.3.0 <3.0.0'
  path: '>=1.8.0 <3.0.0'
  synchronized: '>=3.0.0 <5.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  http: '>=0.13.0'
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  build_runner: '>=1.11.3'
  build_web_compilers: '>=2.16.4'
  build_test: '>=1.3.6'
  # Tool
  yaml: '>=3.0.0'
  pub_semver:
